### ISSUE TITLE
How to get the id after searching for a series by name?

### ISSUE THREAD

**Issue by droidzone** [adrenth/thetvdb2#10]
Code:

```
$client = new \Adrenth\Thetvdb\Client();
$token = $client->authentication()->login($apiKey, $username, $userKey);
$client->setToken($token);
$client->setLanguage('en');
$search=$client->search()->seriesByName($string)->getData();
print_r $search[0];
```

This returns a private array:
```
Adrenth\Thetvdb\Model\Series Object
(
    [values:Adrenth\Thetvdb\Model\ValueObject:private] => Array
        (
            [aliases] => Array
                (
                    [0] => Doctor Who (1963)
                    [1] => Dr Who
                )

            [banner] => graphical/76107-g14.jpg
            [firstAired] => 1963-11-23
            [id] => 76107
            [network] => BBC One
            [overview] => Doctor Who is the longest-running science fiction TV series in history, airing initially from 1963 to 1989.  Doctor Who is about ideas.  It pioneered sophisticated mixed-level storytelling. Its format was the key to its longevity: the Doctor, a mysterious traveller in space and time, travels in his ship, the TARDIS.  The TARDIS can take him and his companions anywhere in time and space. Inevitably he finds evil at work wherever he goes...
            [seriesName] => Doctor Who
            [status] => Ended
        )

)
```

**Comment by trickster2012** [comment]
It's in a the Series Object,
To Get the ID for the serie you found:
`<?php

$client = new \Adrenth\Thetvdb\Client();
$token = $client->authentication()->login($apiKey, $username, $userKey);
$client->setToken($token);
$client->setLanguage('en');
$search=$client->search()->seriesByName($string);

$search->getSeriesId();

?>
`

I Hope this response is not to late ;)

**Comment by mariobernheim** [comment]
I'm having the same issue except its not with seriesbyname, its with seriesByImdbId();
```
$search=$client->search()->seriesByImdbId($imdb_id);
$theSeriesId = $search->getSeriesId();
```

this returns the following:

`
Fatal error: Uncaught Adrenth\Thetvdb\Exception\InvalidArgumentException: Undefined attribute seriesId in class Adrenth\Thetvdb\Model\SeriesData in /vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Exception/InvalidArgumentException.php:37 Stack trace: #0 /root/download_panel/vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Model/ValueObject.php(88): Adrenth\Thetvdb\Exception\InvalidArgumentException::undefinedAttribute('seriesId', 'Adrenth\\Thetvdb...') #1 /scan.php(49): Adrenth\Thetvdb\Model\ValueObject->__call('getSeriesId', Array) #2 {main} thrown in /vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Exception/InvalidArgumentException.php on line 37`

its late... sorry if I'm asking something stupid 🤣
