### ISSUE TITLE
Using in another PHP file

### ISSUE THREAD

**Issue by brandbrilliance** [adrenth/thetvdb2#13]
I'm not very skilled with namespaces, autloaders and stuff. How can I replace a very outdated v1 api class with your class. your package has many, many, many files, and do I now have to load them all using require statements. I tried a bit, but it just keeps generating errors on various lines in your code, no matter how i include the library. I don't use anything but a custom written .php file that I'm using to rename files.

**Comment by DariusIII** [comment]
Yous should start to use [composer](https://getcomposer.org/) to manage your dependencies.
