### ISSUE TITLE
getEpisodesSummary

### ISSUE THREAD

**Issue by johanneshro** [adrenth/thetvdb2#15]
How can i get the Values from the getEpisodesSummary Method?

$client->series()->getEpisodesSummary($result->getId()); will work

$client->series()->getEpisodesSummary($result->getId())->getData(); will not work
$client->series()->getEpisodesSummary($result->getId())->getData()-all(); will not work
$client->series()->getEpisodesSummary($result->getId())->getData(); will not work
$client->series()->getEpisodesSummary($result->getId())->getData()-all()->getAiredSeasons() will not work

**Comment by adrenth** [comment]
See the DocBlock:
```
/**
 * Class SeriesEpisodesSummary
 *
 * @category Thetvdb
 * @package  Adrenth\Thetvdb\Model
 * @author   Alwin Drenth <adrenth@gmail.com>
 * @license  http://opensource.org/licenses/MIT The MIT License (MIT)
 * @link     https://github.com/adrenth/thetvdb2
 *
 * @method array getAiredSeasons()
 * @method int getAiredEpisodes()
 * @method array getDvdSeasons()
 * @method int getDvdEpisodes()
 */
```

```
$response = $client->series()->getEpisodesSummary(70366);

$response->getAiredEpisodes();
$response->getAiredSeasons();
$response->getDvdEpisodes();
$response->getDvdSeasons();
```
