### ISSUE TITLE
How to get ID after searching search()->seriesByImdbID("tt123457890");

### ISSUE THREAD

**Issue by mariobernheim** [adrenth/thetvdb2#23]
Hi, didn't notice I had posted previously on a closed issue
I'm  having a hard time extracting the data from a search result with seriesByImdbId

I'm having the same issue except its not with seriesbyname, its with seriesByImdbId();

```
$search=$client->search()->seriesByImdbId($imdb_id);
$theSeriesId = $search->getSeriesId();
```
this returns the following:

`Fatal error: Uncaught Adrenth\Thetvdb\Exception\InvalidArgumentException: Undefined attribute seriesId in class Adrenth\Thetvdb\Model\SeriesData in /vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Exception/InvalidArgumentException.php:37 Stack trace: #0 /vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Model/ValueObject.php(88): Adrenth\Thetvdb\Exception\InvalidArgumentException::undefinedAttribute('seriesId', 'Adrenth\\Thetvdb...') #1 /scan.php(49): Adrenth\Thetvdb\Model\ValueObject->__call('getSeriesId', Array) #2 {main} thrown in /vendor/adrenth/thetvdb2/src/Adrenth/Thetvdb/Exception/InvalidArgumentException.php on line 37`

its late... sorry if I'm asking something stupid 🤣

**Comment by OskarStark** [comment]
Maybe this helps:

```php
$series = $client->search()->seriesByName($imdb_id);

/** @var Series $first */
$first = $series->getData()->first();
        
print_r($first->getId());
```
